#include <dmcre/crypto.hpp>

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <cmath>

extern "C" {
	#include "crypto/b-con/sha1.h"
	#include "crypto/b-con/sha256.h"
}

//*				IMPLEMENTATION UTIL				*//
//*				IMPLEMENTATION UTIL				*//
//*				IMPLEMENTATION UTIL				*//
//*				IMPLEMENTATION UTIL				*//
//*				IMPLEMENTATION UTIL				*//
static inline void ModifyBitInBuffer(void* buf, uint64_t pos, bool value) {
	uint8_t* byte = ((uint8_t*)buf) + (pos / 8);
	uint8_t mask = 1 << (7 - (pos % 8));
	if(value) {
		*byte |= mask;
	} else {
		*byte &= ~mask;
	}
}

template<typename T>
static inline void ByteSwap(T* in, T* out) {
	uint8_t* _in = (uint8_t*)in;
	uint8_t* _out = (uint8_t*)out;
	for(uint64_t _pi = 0, _po = sizeof(T)-1;_pi<sizeof(T);_pi++,_po--) {
		_out[_po] = _in[_pi];
	}
}

namespace dmcre::crypto {

namespace sha {
//+				SHA					+//
//+				SHA					+//
//+				SHA					+//
//+				SHA					+//
//+				SHA					+//
// source of truth: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf
/*
1. INTRODUCTION
This Standard specifies secure hash algorithms, SHA-1, SHA-224, SHA-256, SHA-384, SHA-
512, SHA-512/224 and SHA-512/256. All of the algorithms are iterative, one-way hash
functions that can process a message to produce a condensed representation called a message
digest. These algorithms enable the determination of a message’s integrity: any change to the
message will, with a very high probability, result in a different message digest. This property is
useful in the generation and verification of digital signatures and message authentication codes,
and in the generation of random numbers or bits.

Each algorithm can be described in two stages: preprocessing and hash computation.
Preprocessing involves padding a message, parsing the padded message into m-bit blocks, and
setting initialization values to be used in the hash computation. The hash computation generates
a message schedule from the padded message and uses that schedule, along with functions,
constants, and word operations to iteratively generate a series of hash values. The final hash
value generated by the hash computation is used to determine the message digest.

The algorithms differ most significantly in the security strengths that are provided for the data
being hashed. The security strengths of these hash functions and the system as a whole when
each of them is used with other cryptographic algorithms, such as digital signature algorithms
and keyed-hash message authentication codes, can be found in [SP 800-57] and [SP 800-107].

Additionally, the algorithms differ in terms of the size of the blocks and words of data that are
used during hashing or message digest sizes. Figure 1 presents the basic properties of these hash
algorithms.

+---------------+----------------+------------+------------+---------------------+
| Algorithm     | Message Size   | Block Size | Word Size  | Message Digest Size |
|               |   (bits)       |   (bits)   |   (bits)   |       (bits)        |
+---------------+----------------+------------+------------+---------------------+
| SHA-1         | < 2^64         |    512     |     32     |         160         |
| SHA-224       | < 2^64         |    512     |     32     |         224         |
| SHA-256       | < 2^64         |    512     |     32     |         256         |
| SHA-384       | < 2^128        |   1024     |     64     |         384         |
| SHA-512       | < 2^128        |   1024     |     64     |         512         |
| SHA-512/224   | < 2^128        |   1024     |     64     |         224         |
| SHA-512/256   | < 2^128        |   1024     |     64     |         256         |
+---------------+----------------+------------+------------+---------------------+

*/
struct AlgoConstants {
	// bits
	uint64_t MessageSizeMax;
	// bits
	uint64_t BlockSize;
	// bits
	uint64_t WordSize;
	// bits
	uint64_t MessageDigestSize;
};

AlgoConstants sha1 = {
	.MessageSizeMax = 0xFFFFFFFFFFFFFFFF,
	.BlockSize = 512,
	.WordSize = 32,
	.MessageDigestSize = 160
};

AlgoConstants sha224 = {
	.MessageSizeMax = 0xFFFFFFFFFFFFFFFF,
	.BlockSize = 512,
	.WordSize = 32,
	.MessageDigestSize = 224
};

AlgoConstants sha256 = {
	.MessageSizeMax = 0xFFFFFFFFFFFFFFFF,
	.BlockSize = 512,
	.WordSize = 32,
	.MessageDigestSize = 256
};

AlgoConstants sha384 = {
	.MessageSizeMax = 0xFFFFFFFFFFFFFFFF,
	.BlockSize = 1024,
	.WordSize = 64,
	.MessageDigestSize = 384
};

AlgoConstants sha512 = {
	.MessageSizeMax = 0xFFFFFFFFFFFFFFFF,
	.BlockSize = 1024,
	.WordSize = 64,
	.MessageDigestSize = 512
};

AlgoConstants sha512_224 = {
	.MessageSizeMax = 0xFFFFFFFFFFFFFFFF,
	.BlockSize = 1024,
	.WordSize = 64,
	.MessageDigestSize = 224
};

AlgoConstants sha512_256 = {
	.MessageSizeMax = 0xFFFFFFFFFFFFFFFF,
	.BlockSize = 1024,
	.WordSize = 64,
	.MessageDigestSize = 256
};

/*
4.1.1 SHA-1 Functions

SHA-1 uses a sequence of logical functions, f₀, f₁, …, f₇₉. Each function ft, where 0 ≤ t ≤ 79, operates on three 32-bit words x, y, and z, and produces a 32-bit word as output. The function ft(x, y, z) is defined as follows:
	•	Ch(x, y, z) = (x ∧ y) ⊕ (¬x ∧ z), for 0 ≤ t ≤ 19
	•	Parity(x, y, z) = x ⊕ y ⊕ z,     for 20 ≤ t ≤ 39
	•	Maj(x, y, z) = (x ∧ y) ⊕ (x ∧ z) ⊕ (y ∧ z), for 40 ≤ t ≤ 59
	•	Parity(x, y, z) = x ⊕ y ⊕ z,     for 60 ≤ t ≤ 79
*/
uint32_t sha1_f(uint64_t t, uint32_t x, uint32_t y, uint32_t z) {
	if((0 <= t) && (t <= 19)) {
		return ((x & y) ^ (~x & z));
	} else if((20 <= t) && (t <= 39)) {
		return (x ^ y ^ z);
	} else if((40 <= t) && (t <= 59)) {
		return ((x & y) ^ (x & z) ^ (y & z));
	} else if((60 <= t) && (t <= 79)) {
		return (x ^ y ^ z);
	}
	abort();
}

uint32_t sha1_k(uint64_t t) {
	//__builtin_bswap32
	if(0 <= t && t <= 19) {
		return (0x5a827999);
	} else if(20 <= t && t <= 39) {
		return (0x6ed9eba1);
	} else if(40 <= t && t <= 59) {
		return (0x8f1bbcdc);
	} else if(60 <= t && t <= 79) {
		return (0xca62c1d6);
	}
	abort();
}

/*
The following operations are used in the secure hash algorithm specifications:

ROTLn(x)
The rotate left (circular left shift) operation, where x is a w-bit word and n is an integer with 0 ≤ n < w, is defined by:
ROTLn(x) = (x << n) ∨ (x >> (w − n))

ROTRn(x)
The rotate right (circular right shift) operation, where x is a w-bit word and n is an integer with 0 ≤ n < w, is defined by:
ROTRn(x) = (x >> n) ∨ (x << (w − n))

*/

template<typename T,int n>
T ROTL(const T x) {
	constexpr uint64_t w = sizeof(T)*8;
	static_assert(0 <= n && n < w, "assertion failed: 0 <= n < w");
	uint32_t BE_X = __builtin_bswap32(x);
	return __builtin_bswap32((BE_X << n) | (BE_X >> (w - n)));
}

template<typename T,int n>
T ROTR(const T x) {
	constexpr uint64_t w = sizeof(T)*8;
	static_assert(0 <= n && n < w, "assertion failed: 0 <= n < w");
	uint32_t BE_X = __builtin_bswap32(x);
	return __builtin_bswap32((BE_X >> n) | (BE_X << (w - n)));
}

/*

5. PREPROCESSING
Preprocessing consists of three steps: padding the message, M (Sec. 5.1), parsing the message
into message blocks (Sec. 5.2), and setting the initial hash value, H(0) (Sec. 5.3).

5.1 Padding the Message
The purpose of this padding is to ensure that the padded message is a multiple of 512 or 1024
bits, depending on the algorithm. Padding can be inserted before hash computation begins on a
message, or at any other time during the hash computation prior to processing the block(s) that
will contain the padding.

*/

/*

5.1.1 SHA-1, SHA-224 and SHA-256

Suppose that the length of the message, M, is ℓ bits.
Append the bit “1” to the end of the message, followed by k zero bits, where k is the smallest
non-negative solution to the equation:

    ℓ + 1 + k ≡ 448 mod 512

Then append the 64-bit block that is equal to the number ℓ expressed using a binary representation.

For example, the (8-bit ASCII) message "abc" has length:

    ℓ = 3 × 8 = 24 bits

So the message is padded with a one bit, then:

    k = 448 − (ℓ + 1) = 448 − 25 = 423 zero bits

And then the 64-bit binary representation of the length (24) is appended.

The resulting 512-bit padded message becomes:

    01100001 01100010 01100011 1 0000...0000 000...011000
    [   a   ] [   b   ] [   c   ] 1 [ 423 zero bits ] [64-bit length: 000...011000]

Where:
    "a" = 0x61 = 01100001
    "b" = 0x62 = 01100010
    "c" = 0x63 = 01100011
    ℓ = 24 (in binary: 000...011000)

Thus the final message is:
    3 bytes of data + 1 '1' bit + 423 '0' bits + 64-bit length field = 512 bits total.

*/

/**
	@brief pads the message according to section 5.1.1
*/
HashBuffer PadMessage_5_1_1(const HashBuffer& M) {
	HashBuffer output(nullptr,0);

	const uint64_t ℓ = M.Size;
	const uint64_t k = 447 - (ℓ % 512);

	output.Size = (ℓ + 1 + k + 64) / 8;

	output.Data = calloc(1,output.Size);

	memcpy(output.Data,M.Data,ceil(M.Size / 8.0));
	ModifyBitInBuffer(output.Data, ℓ, 1);
	const uint64_t ℓ_BE = __builtin_bswap64(ℓ);

	memcpy(((uint8_t*)output.Data)+(output.Size-sizeof(ℓ_BE)),&ℓ_BE,sizeof(ℓ_BE));

	return output;
}

/*
5.1.2 SHA-384, SHA-512, SHA-512/224 and SHA-512/256

Suppose the length of the message M, in bits, is ℓ bits. 
Append the bit “1” to the end of the message, followed by k zero bits, where k is the smallest 
non-negative solution to the equation:

    ℓ + 1 + k ≡ 896 mod 1024

Then append the 128-bit block that is equal to the number ℓ expressed using a binary representation.

For example, the (8-bit ASCII) message "abc" has length:

    ℓ = 3 × 8 = 24 bits

So the message is padded with a one bit, then:

    k = 896 − (ℓ + 1) = 896 − 25 = 871 zero bits

And then a 128-bit binary representation of the length (24) is appended.

The resulting 1024-bit padded message becomes:

    01100001 01100010 01100011 1 0000...0000 000...011000
    [   a   ] [   b   ] [   c   ] 1 [ 871 zero bits ] [128-bit length: 000...011000]

Where:
    "a" = 0x61 = 01100001
    "b" = 0x62 = 01100010
    "c" = 0x63 = 01100011
    ℓ = 24 (in binary: 000...011000, left-padded to 128 bits)

Total:
    3 bytes of data + 1 '1' bit + 871 '0' bits + 128-bit length field = 1024 bits

The length of the padded message is now a multiple of 1024 bits.
*/

/**
	@brief pads the message according to section 5.1.2
	@note this function only supports ℓ <= 2^64 on account of most CPUs not supporting integers wider than 64 bits, this will be changed once hardware support allows for it
	@note as such, the upper 64 bits of ℓ i in the padded message will always be clear
*/
HashBuffer PadMessage_5_1_2(const HashBuffer& M) {
	HashBuffer output(nullptr,0);

	const uint64_t ℓ = M.Size;
	const uint64_t k = 895 - (ℓ % 1024);

	output.Size = (ℓ + 1 + k + 128) / 8;
	output.Data = calloc(1,output.Size);

	memcpy(output.Data,M.Data,ceil(M.Size / 8.0));
	ModifyBitInBuffer(output.Data, ℓ, 1);
	const uint64_t ℓ_BE = __builtin_bswap64(ℓ);
	memcpy((uint8_t*)output.Data+output.Size-sizeof(ℓ_BE),&ℓ_BE,sizeof(ℓ_BE));

	return output;
}

/*
5.2 Parsing the Message
The message and its padding must be parsed into N m-bit blocks.
*/

/*
5.2.1 SHA-1, SHA-224 and SHA-256

For SHA-1, SHA-224, and SHA-256, the message and its padding are parsed into N 512-bit
blocks:

    M(1), M(2), ..., M(N)

Each 512-bit message block M(i) is divided into sixteen 32-bit words, labeled as follows:

    M(i)_0, M(i)_1, M(i)_2, ..., M(i)_15

That is, the first 32 bits of message block i are denoted M(i)_0, the next 32 bits are M(i)_1, 
and so on up to M(i)_15.
*/

/*
5.2.2 SHA-384, SHA-512, SHA-512/224 and SHA-512/256

For SHA-384, SHA-512, SHA-512/224, and SHA-512/256, the message and its padding are 
parsed into N 1024-bit blocks:

    M(1), M(2), ..., M(N)

Each 1024-bit message block M(i) is divided into sixteen 64-bit words, labeled as:

    M(i)_0, M(i)_1, M(i)_2, ..., M(i)_15

That is, the first 64 bits of message block i are denoted M(i)_0, the next 64 bits are M(i)_1,
and so on up to M(i)_15.
*/

class ParsedMessage {
public:
	/**
		@brief word size in bytes, this assumes that no algorithm in the sha family will ever define a word size that isnt a multiple of 8 bits, that would be silly :3
	*/
	const uint64_t WordSize;
	void* WordData;
	ParsedMessage(uint64_t WordSize): WordSize(WordSize){}

	~ParsedMessage() {
		free(this->WordData);
	}

	class Block {
	public:
		uint8_t* words[16];
	};

	Block* Blocks;
	uint64_t BlockCount;
};

ParsedMessage ParseMessage(const HashBuffer& Message,AlgoConstants algo) {
	ParsedMessage output(algo.WordSize / 8);
	output.BlockCount = Message.Size / (algo.BlockSize / 8);
	output.Blocks = new ParsedMessage::Block[output.BlockCount];
	uint8_t* WordData = (uint8_t*)malloc(Message.Size);
	output.WordData = WordData;
	uint8_t* Data = (uint8_t*)Message.Data;
	for(uint64_t b = 0;b < output.BlockCount;b++) {
		for (uint64_t i = 0;i<16;i++) {
			output.Blocks[b].words[i] = WordData;
			WordData+=output.WordSize;
			memcpy(
				output.Blocks[b].words[i],
				Data,
				output.WordSize
			);
			Data+=output.WordSize;
		}
	}
	return output;
}

/*
5.3 Setting the Initial Hash Value (H(0))
------------------------------------------

Before hash computation begins for each of the secure hash algorithms, 
the initial hash value, H(0), must be set. The size and number of words 
in H(0) depends on the message digest size.

5.3.1 SHA-1
-----------

For SHA-1, the initial hash value H(0) shall consist of the following 
five 32-bit words, in hexadecimal:

    H0(0) = 67452301  
    H1(0) = efcdab89  
    H2(0) = 98badcfe  
    H3(0) = 10325476  
    H4(0) = c3d2e1f0

5.3.2 SHA-224
-------------

For SHA-224, the initial hash value H(0) shall consist of the following 
eight 32-bit words, in hexadecimal:

    H0(0) = c1059ed8  
    H1(0) = 367cd507  
    H2(0) = 3070dd17  
    H3(0) = f70e5939
    H4(0) = ffc00b31  
    H5(0) = 68581511  
    H6(0) = 64f98fa7  
    H7(0) = befa4fa4

5.3.3 SHA-256
-------------

For SHA-256, the initial hash value H(0) shall consist of the following 
eight 32-bit words, in hexadecimal:

    H0(0) = 6a09e667
    H1(0) = bb67ae85
    H2(0) = 3c6ef372
    H3(0) = a54ff53a
    H4(0) = 510e527f
    H5(0) = 9b05688c
    H6(0) = 1f83d9ab
    H7(0) = 5be0cd19

These words were obtained by taking the first 32 bits of the fractional 
parts of the square roots of the first eight prime numbers.

5.3.4 SHA-384
-------------

For SHA-384, the initial hash value H(0) shall consist of the following 
eight 64-bit words, in hexadecimal:

    H0(0) = cbbb9d5dc1059ed8  
    H1(0) = 629a292a367cd507  
    H2(0) = 9159015a3070dd17  
    H3(0) = 152fecd8f70e5939  
    H4(0) = 67332667ffc00b31  
    H5(0) = 8eb44a8768581511  
    H6(0) = db0c2e0d64f98fa7  
    H7(0) = 47b5481dbefa4fa4

These words were obtained by taking the first 64 bits of the fractional 
parts of the square roots of the 9th through 16th prime numbers.

5.3.5 SHA-512
-------------

For SHA-512, the initial hash value H(0) shall consist of the following 
eight 64-bit words, in hexadecimal:

    H0(0) = 6a09e667f3bcc908  
    H1(0) = bb67ae8584caa73b  
    H2(0) = 3c6ef372fe94f82b  
    H3(0) = a54ff53a5f1d36f1  
    H4(0) = 510e527fade682d1  
    H5(0) = 9b05688c2b3e6c1f  
    H6(0) = 1f83d9abfb41bd6b  
    H7(0) = 5be0cd19137e2179

These words were obtained by taking the first 64 bits of the fractional 
parts of the square roots of the first eight prime numbers.

5.3.6 SHA-512/t
---------------

“SHA-512/t” refers to a family of t-bit hash functions based on SHA-512, 
with their outputs truncated to t bits. Each function in this family requires 
a unique initial hash value. This section provides a method to compute the 
initial value for SHA-512/t, given a specific value of t.

- t must be a positive integer with no leading zeros.
- t must be less than 512 and must not be 384.
- For example, t = 256 is valid, but t = 0256 is not.
- The string "SHA-512/256" is 11 characters long and has the following ASCII hex representation:

      "SHA-512/256" = 53 48 41 2D 35 31 32 2F 32 35 36

Initial Hash Value Generation Procedure for SHA-512/t:
------------------------------------------------------

Let H(0)'   = the initial hash value from SHA-512 (as given in section 5.3.5).  
Let H(0)''  = an intermediate IV derived from H(0)' by XORing each word with the 
             constant 0xa5a5a5a5a5a5a5a5 (in hex).

For i = 0 to 7:
    H''i(0) = H'i(0) XOR a5a5a5a5a5a5a5a5

Then:
    H(0) = SHA-512("SHA-512/t") using H(0)'' as the IV

    (The input string "SHA-512/t" is ASCII encoded as described above, where t is the 
    specific truncation value like 224 or 256.)

Approved Variants:
------------------

The following SHA-512/t variants are currently approved:

    - SHA-512/224 (t = 224)
    - SHA-512/256 (t = 256)

Other values of t may be approved in the future and published in NIST SP 800-107.

5.3.6.1 SHA-512/224
-------------------

For SHA-512/224, the initial hash value H(0) shall consist of the following 
eight 64-bit words, in hexadecimal:

    H0(0) = 8C3D37C819544DA2  
    H1(0) = 73E1996689DCD4D6  
    H2(0) = 1DFAB7AE32FF9C82  
    H3(0) = 679DD514582F9FCF  
    H4(0) = 0F6D2B697BD44DA8  
    H5(0) = 77E36F7304C48942  
    H6(0) = 3F9D85A86A1D36C8  
    H7(0) = 1112E6AD91D692A1

These words were obtained by executing the SHA-512/t IV Generation Function 
with t = 224.

5.3.6.2 SHA-512/256
-------------------

For SHA-512/256, the initial hash value H(0) shall consist of the following 
eight 64-bit words, in hexadecimal:

    H0(0) = 22312194FC2BF72C  
    H1(0) = 9F555FA3C84C64C2  
    H2(0) = 2393B86B6F53B151  
    H3(0) = 963877195940EABD  
    H4(0) = 96283EE2A88EFFE3  
    H5(0) = BE5E1E2553863992  
    H6(0) = 2B0199FC2C85B8AA  
    H7(0) = 0EB72DDC81C52CA2

These words were obtained by executing the SHA-512/t IV Generation Function 
with t = 256.

*/

/*
6. SECURE HASH ALGORITHMS
--------------------------

In the following sections, the hash algorithms are not described in ascending order of size. 
SHA-256 is described before SHA-224 because the specification for SHA-224 is identical 
to SHA-256, except that different initial hash values are used, and the final hash value is 
truncated to 224 bits for SHA-224.

The same is true for SHA-512, SHA-384, SHA-512/224, and SHA-512/256, except that the 
final hash value is truncated to:
    - 224 bits for SHA-512/224,
    - 256 bits for SHA-512/256, or
    - 384 bits for SHA-384.

For each of the secure hash algorithms, there may exist alternate computation methods 
that yield identical results; one example is the alternative SHA-1 computation described 
in Section 6.1.3. Such alternate methods may be implemented in conformance to this 
standard.
*/

/*
6.1 SHA-1
---------

SHA-1 may be used to hash a message, M, having a length of ℓ bits, where 0 < ℓ ≤ 2^64.

The algorithm uses:
  1. A message schedule of eighty 32-bit words,
  2. Five working variables of 32 bits each, and
  3. A hash value of five 32-bit words.

The final result of SHA-1 is a 160-bit message digest.

- The words of the message schedule are labeled W0, W1, ..., W79.
- The five working variables are labeled: a, b, c, d, and e.
- The words of the hash value are labeled: H0(i), H1(i), ..., H4(i), which:
    - Initially hold the initial hash value H(0),
    - Are updated to each successive intermediate hash value H(i),
    - And finally become the final hash value H(N) after all message blocks are processed.

SHA-1 also uses a single temporary word, T.

6.1.1 SHA-1 Preprocessing
-------------------------

1. Set the initial hash value H(0) as specified in Section 5.3.1.
2. The message is padded and parsed as specified in Section 5.

6.1.2 SHA-1 Hash Computation
----------------------------

The SHA-1 hash computation uses functions and constants defined in Section 4.1.1 and 4.2.1.
All additions (+) are performed modulo 2^32.

Each message block, M(1), M(2), ..., M(N), is processed in order using the following steps:

For i = 1 to N:

1. Prepare the message schedule {Wt}:
   For t = 0 to 15:
       Wt = M(i)t
   For t = 16 to 79:
       Wt = ROTL1(Wt-3 ⊕ Wt-8 ⊕ Wt-14 ⊕ Wt-16)

2. Initialize the five working variables a, b, c, d, and e with the (i−1)st hash value:
       a = H0(i−1)
       b = H1(i−1)
       c = H2(i−1)
       d = H3(i−1)
       e = H4(i−1)

3. For t = 0 to 79:
   {
       T = ROTL5(a) + ft(b, c, d) + e + Kt + Wt
       e = d
       d = c
       c = ROTL30(b)
       b = a
       a = T
   }

4. Compute the ith intermediate hash value H(i):
       H0(i) = H0(i−1) + a
       H1(i) = H1(i−1) + b
       H2(i) = H2(i−1) + c
       H3(i) = H3(i−1) + d
       H4(i) = H4(i−1) + e

After repeating steps 1 through 4 for all N message blocks, the final 160-bit message digest is:

       H0(N) || H1(N) || H2(N) || H3(N) || H4(N)

*/

HashBuffer compute_sha1(const ParsedMessage& p) {
	uint32_t** H = new uint32_t*[5];
	void* H_buff = calloc(5,sizeof(uint32_t[p.BlockCount+1]));
	for(uint64_t i = 0;i<5;i++) {
		H[i] = (uint32_t*)(((uint8_t*)H_buff)+(i*sizeof(uint32_t[p.BlockCount+1])));
	}
	H[0][0] = (0x67452301);
	H[1][0] = (0xefcdab89);
	H[2][0] = (0x98badcfe);
	H[3][0] = (0x10325476);
	H[4][0] = (0xc3d2e1f0);

	auto M = (ParsedMessage::Block*)calloc(1,sizeof(ParsedMessage::Block[p.BlockCount+1]));
	memcpy(M+1,p.Blocks,sizeof(ParsedMessage::Block[p.BlockCount]));
	auto N = p.BlockCount;
	for(uint64_t i = 1;i<=N;i++) {
		uint32_t W[80];
		/*
		1. Prepare the message schedule {Wt}:
		   For t = 0 to 15:
		       Wt = M(i)t
		   For t = 16 to 79:
		       Wt = ROTL1(Wt-3 ⊕ Wt-8 ⊕ Wt-14 ⊕ Wt-16)
		*/
		for(uint64_t t = 0;t<16;t++) {
			W[t] = *((uint32_t*)(M[i].words[t]));
		}
		for(uint64_t t = 16;t<80;t++) {
			W[t] = ROTL<uint32_t,1>(W[t-3] ^ W[t-8] ^ W[t - 14] ^ W[t-16]);
		}

		/*
		2. Initialize the five working variables a, b, c, d, and e with the (i−1)st hash value:
       		a = H0(i−1)
       		b = H1(i−1)
       		c = H2(i−1)
       		d = H3(i−1)
       		e = H4(i−1)
		*/
		uint32_t a = H[0][i - 1];
       	uint32_t b = H[1][i - 1];
       	uint32_t c = H[2][i - 1];
       	uint32_t d = H[3][i - 1];
       	uint32_t e = H[4][i - 1];

		/*
		3. For t = 0 to 79:
       		T = ROTL5(a) + ft(b, c, d) + e + Kt + Wt
       		e = d
       		d = c
       		c = ROTL30(b)
       		b = a
       		a = T
		*/
		for(uint64_t t = 0;t<80;t++) {
			const uint32_t T = ROTL<uint32_t,5>(a) + sha1_f(t, b, c, d) + e + sha1_k(t) + W[t];
       		e = d;
       		d = c;
       		c = ROTL<uint32_t,30>(b);
       		b = a;
       		a = T;
		}

		/*
		4. Compute the ith intermediate hash value H(i):
    		H0(i) = H0(i−1) + a
    		H1(i) = H1(i−1) + b
    		H2(i) = H2(i−1) + c
    		H3(i) = H3(i−1) + d
    		H4(i) = H4(i−1) + e
		*/
		H[0][i] = H[0][i-1] + a;
    	H[1][i] = H[1][i-1] + b;
    	H[2][i] = H[2][i-1] + c;
    	H[3][i] = H[3][i-1] + d;
    	H[4][i] = H[4][i-1] + e;
	}

	HashBuffer out(malloc(160/8),160/8);
	uint32_t* final = (uint32_t*)out.Data;
	final[0] = H[0][N];
	final[1] = H[1][N];
	final[2] = H[2][N];
	final[3] = H[3][N];
	final[4] = H[4][N];

	free(M);
	return out;
}

//+ namespace: sha
}

	//const HashAlgorithm sha1([](void* Data,uint64_t DataSize) {
	//	HashBuffer in(Data,DataSize);
	//	HashBuffer pm = sha::PadMessage_5_1_1(in);
	//	sha::ParsedMessage p = sha::ParseMessage(pm, sha::sha1);
	//	HashBuffer out = sha::compute_sha1(p);
	//	return out;
	//});
	const HashAlgorithm sha1([](void* Data,uint64_t DataSize) {
    	SHA1_CTX ctx;
    	uint8_t* hash = (uint8_t*)malloc(20);
    	if (!hash) abort();
    	sha1_init(&ctx);
    	sha1_update(&ctx, (const BYTE*)Data, (size_t)DataSize);
    	sha1_final(&ctx,hash);
    	return HashBuffer(hash,160/8);
	});

	const HashAlgorithm sha256([](void* Data,uint64_t DataSize) {
    	SHA256_CTX ctx;
    	uint8_t* hash = (uint8_t*)malloc(256/8);
    	if (!hash) abort();
    	sha256_init(&ctx);
    	sha256_update(&ctx, (const BYTE*)Data, (size_t)DataSize);
    	sha256_final(&ctx,hash);
    	return HashBuffer(hash,256/8);
	});

	const HashAlgorithm sha224([](void* Data,uint64_t DataSize) {
    	SHA256_CTX ctx;
    	uint8_t* hash = (uint8_t*)malloc(256/8);
    	if (!hash) abort();
    	sha256_init(&ctx);
    	sha256_update(&ctx, (const BYTE*)Data, (size_t)DataSize);
    	sha256_final(&ctx,hash);
    	return HashBuffer(hash,224/8);
	});



//, namespace: crypto
}
